[package]
name = "rustlb"
version = "0.1.0"
authors = ["Bhargav Voleti <bhargav.voleti93@gmail.com>"]
edition = "2018"

[dependencies]
romio = "0.3.0-alpha.2"
futures-preview = "0.3.0-alpha.13"
rand = "0.6.5"
